/* ملف مُستخرج تلقائيًا من Dashboard.jsx — قسم: changelog-legal-data */

/* ── ١٠. سجل إصدارات الموقع (CHANGELOG) ──
   ترقيم الإصدارات بنظام "رئيسي.فرعي.تصحيحي" (Major.Minor.Patch)، مثل مواقع البرمجيات المعتادة:
     • يرتفع الرقم التصحيحي (مثل 1.1.1 → 1.1.2) مع أي تعديل صغير: إصلاح مشكلة،
       حذف/تعديل عنصر بسيط، تحسين نص أو تصميم — وهذا الغالب، يشمل أغلب الطلبات اليومية.
     • يرتفع الرقم الفرعي ويُصفَّر التصحيحي (مثل 1.1.4 → 1.2.0) عند إضافة ميزة جديدة
       فعلية (مثل لوحة أو خانة جديدة داخل تبويب موجود).
     • يرتفع الرقم الرئيسي ويُصفَّر البقية (مثل 1.x.x → 2.0.0) فقط عند تغيير جوهري
       كبير: إعادة تصميم شاملة، أو إضافة قسم/تبويب رئيسي جديد للوحة.
   عند كل تحديث كود مستقبلي على هذا الملف — مهما كان صغيرًا — يُضاف عنصر جديد
   بالأعلى برقم إصدار تالٍ حسب القاعدة أعلاه. لا تُعاد كتابة أو حذف الإصدارات السابقة. */
export const CHANGELOG = [
  {
    version: "2.10.1",
    dateAr: "25 سبتمبر 2026",
    dateEn: "September 25, 2026",
    ar: [
      "إصلاحات: إعادة تنظيم داخلية لملفات الكود (تقسيم الملف الرئيسي لملفات أصغر) لتسهيل الصيانة مستقبلًا — بدون أي تغيير على شكل الموقع أو وظائفه",
    ],
    en: [
      "Fixes: internal code reorganization (split the main file into smaller files) to ease future maintenance — no change to the site's look or behavior",
    ],
  },
  {
    version: "2.10.0",
    dateAr: "25 سبتمبر 2026",
    dateEn: "September 25, 2026",
    ar: [
      "تصميم ثالث للموقع اسمه \u200f\"بنّاء\"\u200f: كل ملاحظة لبنة في جدار بلون قرارها، والأحدث في أعلى الجدار، واللبنة المفرّغة ما زالت مفتوحة — تضغط أي لبنة وتنفتح ملاحظتها",
      "أسطح مصمتة بلا زجاج ولا تدرّج، وتبويبات مرصوصة كصف لبنات، وعناوين وأرقام بخط كوفي ثقيل — ويشتغل مع أطقم الألوان الخمسة بالفاتح والداكن",
      "لوحة الإدارة ← \u200f\"مظهر الموقع\"\u200f: ثلاث تصاميم تختار منها (الكلاسيكي، نوفا، بنّاء)، والاختيار يوصل لكل الزوّار فورًا",
    ],
    en: [
      "A third site design, \"Bannaa\": every note is a brick in a wall, colored by its decision, newest on top, hollow while still open — tap any brick to open its note",
      "Solid surfaces with no glass or gradients, tabs laid like a course of bricks, and headings and figures in a heavy Kufi face — works with all five color sets, light and dark",
      "Admin panel → \"Site appearance\": three designs to choose from (Classic, Nova, Bannaa); the choice reaches every visitor instantly",
    ],
  },
  {
    version: "2.9.2",
    dateAr: "22 سبتمبر 2026",
    dateEn: "September 22, 2026",
    ar: [
      "صار كل نموذج يقدر ياخذ أكثر من مقطع فيديو، لا مقطع واحد بس — تظهر كلها بعارض النموذج بالترتيب اللي تحدده الإدارة",
      "لوحة الإدارة ← \u200f\"مقاطع النماذج\"\u200f: زر \u200f\"إضافة مقطع\"\u200f منفصل لكل نموذج، وأسهم لأعلى/أسفل لترتيب مقاطع نفس النموذج",
      "بطاقة المخططات تعرض عدد المقاطع لما يكون أكثر من مقطع",
    ],
    en: [
      "Each model can now hold more than one video, not just one — all shown in the model's viewer in the order the admin sets",
      "Admin panel → \"Model videos\": a separate \"Add video\" button per model, with up/down arrows to reorder that model's clips",
      "The plans card shows the video count when a model has more than one",
    ],
  },
  {
    version: "2.9.1",
    dateAr: "22 سبتمبر 2026",
    dateEn: "September 22, 2026",
    ar: [
      "إصلاح: فتح \u200f\"تعديل\"\u200f على استفسار موجود بلوحة الإدارة كان يوقف اللوحة بالكامل — صار يعرض \u200f\"سجل البند\"\u200f: من أضافه، ومن عدّله آخر مرة، وكل تعديل بالحقول اللي تغيّرت (من ← إلى)",
      "إصلاح: الفلاتر المخصصة وتقدّم التنفيذ صارت تتحدّث عند الزوّار لحظيًا فعلًا بعد أي تعديل إداري أو استيراد — قبل كذا كانت تحتاج تحديث الصفحة",
      "تحسين: الاستيراد الكبير (مئات التغييرات خلال ثوانٍ) صار يوصل لكل زائر كتحديث واحد بدل مئات الطلبات",
      "أمان: إنشاء حساب جديد ما عاد يسمح بمنح صلاحيات أعلى من صلاحيات المنشئ نفسه (إلا لصاحب صلاحية \u200f\"تعديل الصلاحيات\"\u200f) — والتحقق بالخادم نفسه، مو بالواجهة فقط",
    ],
    en: [
      "Fix: opening \"Edit\" on an existing inquiry in the admin panel crashed the whole panel — it now shows the item's history: who added it, who last edited it, and every edit with the fields that changed (from → to)",
      "Fix: custom filters and construction progress now truly update live for visitors after any admin edit or import — previously they needed a page refresh",
      "Improvement: a large import (hundreds of changes within seconds) now reaches each visitor as a single update instead of hundreds of requests",
      "Security: creating a new account can no longer grant permissions beyond the creator's own (except for holders of \"Edit permissions\") — enforced on the server itself, not just the UI",
    ],
  },
  {
    version: "2.9.0",
    dateAr: "22 سبتمبر 2026",
    dateEn: "September 22, 2026",
    ar: [
      "جولة فيديو لكل نموذج: مقطع يوتيوب يُعرض داخل عارض النموذج نفسه — أول صفحة قبل الواجهة والمخططات، والبرشور (PDF) بمكانه كما كان",
      "تحميل خفيف: قبل الضغط على \u200f\"تشغيل\"\u200f ما يُحمَّل إلا صورة المقطع — مشغّل يوتيوب يتحمّل عند التشغيل فقط، ويبدأ بضغطة وحدة حتى على الآيفون",
      "النماذج اللي لها مقطع عليها علامة ▶ ومدة المقطع ببطاقة المخططات",
      "لوحة الإدارة ← \u200f\"مقاطع النماذج\"\u200f: لصق أي رابط يوتيوب، تحقق تلقائي إن المقطع يشتغل خارج يوتيوب، جلب العنوان والمدة، إخفاء مؤقت، وعدد مرات التشغيل — وكل تعديل يوصل للزوّار فورًا",
    ],
    en: [
      "A video tour for every model: a YouTube video that plays inside the model's own viewer — the first page, before the exterior and plans, with the brochure (PDF) right where it was",
      "Lightweight: until you tap Play, only the video's image loads — YouTube's player loads on play only, and starts in one tap even on iPhone",
      "Models with a video show a ▶ mark and the video's length on their plans card",
      "Admin panel → \"Model videos\": paste any YouTube link, automatic check that it plays outside YouTube, title and length fetched, temporary hide, and play count — every change reaches visitors instantly",
    ],
  },
  {
    version: "2.8.6",
    dateAr: "17 سبتمبر 2026",
    dateEn: "September 17, 2026",
    ar: [
      "فلتر جديد: \"الاجتماع السادس ميداني\" — البنود التي صدر بشأنها رد في الزيارة الميدانية بتاريخ 17 سبتمبر 2026 (٧ بنود: ٣٠، ٧٦، ٨٥، ٨٨، ٨٩، ٩٠، ٩١)",
      "إصلاح: أي اجتماع جديد يُضاف من تبويب \"الفلاتر\" صار يظهر مباشرة بالموقع العام، حتى قبل ربط أي بند به",
      "إصلاح: الإضافة وإعادة الترتيب بلوحة الفلاتر كانت تعرض \"تمت\" حتى لو الحساب بدون صلاحية وما انحفظ شي — صارت تعرض رسالة واضحة",
    ],
    en: [
      "New filter: \"6th Meeting (Site Visit)\" — items answered during the September 17, 2026 site visit (7 items: 30, 76, 85, 88, 89, 90, 91)",
      "Fix: a new meeting added from the Filters tab now appears on the public site immediately, even before any item is linked to it",
      "Fix: adding or reordering filter values showed success even when the account lacked permission and nothing was saved — it now shows a clear message",
    ],
  },
  {
    version: "2.8.5",
    dateAr: "10 سبتمبر 2026",
    dateEn: "September 10, 2026",
    ar: [
      "تحكم إداري كامل بفئات الفلترة الأساسية (الأولوية، الفئة، الحالة، الجهة المجيبة، الاجتماع) من تبويب \u200f\"الفلاتر\"\u200f بلوحة الإدارة: إضافة قيمة جديدة، إعادة تسمية، حذف، وإعادة ترتيب — بدل ما كانت هذي الفئات مقفلة بالكامل",
      "إعادة التسمية تُحدّث كل استفسار يستخدم القيمة تلقائيًا وفوريًا (وتدمج بذكاء لو سمّيت قيمة باسم موجود أصلاً بدل ما تكرّرها)",
      "الحذف محمي: يرفض ويعرض عدد الاستفسارات المتأثرة لو القيمة مستخدمة فعليًا، ولا ينفّذ إلا بتأكيد صريح",
      "فلاتر الموقع العام (لوحة \u200f\"تخصيص البحث\"\u200f) ونموذج إضافة/تعديل الاستفسار بلوحة الإدارة صارا يقرآن هذي القوائم حيّة من نفس المكان — أي تعديل إداري ينعكس فورًا بدون إعادة نشر",
      "النموذج والموقع مستثنيان حاليًا من التعديل المباشر: قيمتهما نص حر يُصنَّف تلقائيًا بالكود، فيحتاجان تصميمًا مختلفًا — يظهران للعِلم فقط بهذا الإصدار",
    ],
    en: [
      "Full admin control over the core filter categories (priority, category, status, responding engineer, meeting) from the admin panel's Filters tab: add a new value, rename, delete, and reorder — these were previously fully locked",
      "Renaming a value updates every inquiry using it automatically and immediately (and merges intelligently if renamed to an already-existing value instead of duplicating it)",
      "Deleting is protected: it's refused and shows how many inquiries are affected if the value is actually in use, and only proceeds with explicit confirmation",
      "The public site's filters (the \"Customize Search\" panel) and the admin's add/edit-inquiry form now read these lists live from the same place — any admin change reflects immediately with no redeploy",
      "Model and location are excluded from direct editing for now: their values are free text auto-classified by code, which needs a different design — shown for reference only in this release",
    ],
  },
  {
    version: "2.8.4",
    dateAr: "10 سبتمبر 2026",
    dateEn: "September 10, 2026",
    ar: [
      "إعادة تصميم أدوات لوحة المتابعة: بدل صندوق طويل بكل الفلاتر والترتيب مبعثرة فوق القائمة، صار فيه زر واحد \u200f\"الفلاتر والترتيب\"\u200f يفتح لوحة \u200f\"تخصيص البحث\"\u200f منظّمة بأقسام (الحالة، تمييز، الأولوية، الترتيب، التصنيف والنموذج، الموقع والمجيب، التوقيت)",
      "التعديلات داخل لوحة التخصيص مسودة لا تُطبَّق على القائمة إلا بالضغط على زر \u200f\"عرض النتائج\"\u200f — يعرض عدد النتائج المتوقع مباشرة قبل ما تطبّق، فتقدر تجرّب عدة خيارات مرة وحدة بدل ما تعيد القائمة رسم نفسها مع كل ضغطة",
      "مربع البحث النصي يبقى ظاهرًا دائمًا فوق القائمة ويشتغل فورًا كالمعتاد — خارج لوحة التخصيص تمامًا",
      "زر الفلاتر يحمل شارة برقم الفلاتر النشطة (بدون احتساب نص البحث)، مع زر \u200f\"مسح\"\u200f سريع يظهر بجانبه لمسح الفلاتر فقط دون التأثير على نص البحث",
      "الشريط المصغّر اللي يظهر أثناء التمرير لأسفل يفتح نفس لوحة التخصيص مباشرة بدل الرجوع للأعلى",
    ],
    en: [
      "Redesigned the notes-board toolbar: instead of one long box with every filter and sort control laid out above the list, a single \"Filters & sort\" button now opens a \"Customize Search\" panel organized into sections (Status, Flags, Priority, Sort, Category & Model, Location & Engineer, Timing)",
      "Changes inside the customize panel are a draft that only applies to the list when you press \"Show results\" — it shows the expected result count live before you apply, so you can try several options at once instead of the list redrawing after every tap",
      "The text search box stays always visible above the list and works instantly as before — entirely separate from the customize panel",
      "The Filters button carries a badge with the number of active filters (not counting the search text), with a quick \"Clear\" button beside it that clears filters only, leaving your search text untouched",
      "The condensed bar that appears while scrolling down now opens the same customize panel directly instead of jumping back to the top",
    ],
  },
  {
    version: "2.8.3",
    dateAr: "10 سبتمبر 2026",
    dateEn: "September 10, 2026",
    ar: [
      "تصحيح: عند تجاوز الحصة اليومية لخدمة الترجمة المجانية، كانت رسالة تحذير الخدمة نفسها (بالإنجليزية) تُعرض للزائر كأنها ترجمة الملاحظة — ظهر هذا فعليًا بملاحظة واحدة بلوحة \u200f\"نظرة عامة\"\u200f بالعرض الإنجليزي",
      "الموقع صار يتعرّف على رسائل خطأ خدمة الترجمة المعروفة ويتجاهلها، ويعرض النص العربي الأصلي بدلًا منها — تمامًا كما يتصرف مع أي ملاحظة ما توفرت ترجمتها بعد",
      "المعالجة تشمل كل مكان يظهر فيه نص الملاحظة أو الرد بالإنجليزي: البطاقات، الجدول، لوحة التفاصيل، وأحدث الملاحظات بالنظرة العامة",
    ],
    en: [
      "Fixed: when the free translation service's daily quota ran out, its own English warning message was shown to visitors as if it were the note's translation — this actually appeared on one note in English-language \"Overview\"",
      "The site now recognizes known translation-service error messages and ignores them, showing the original Arabic text instead — the same fallback already used for any note without an English translation yet",
      "This covers every place note or reply text appears in English: cards, the table, the detail sheet, and Overview's Latest Notes",
    ],
  },
  {
    version: "2.8.2",
    dateAr: "10 سبتمبر 2026",
    dateEn: "September 10, 2026",
    ar: [
      "تصحيح: على الجوال (خصوصًا سفاري الآيفون) كان رأس لوحة تفاصيل الاستفسار — زر الإغلاق وأزرار السابق/التالي — يختفي فوق حافة الشاشة مع الاستفسارات الطويلة، لأن ارتفاع اللوحة كان يُحسب من ارتفاع الشاشة وأشرطة المتصفح مخفية، بينما المساحة الظاهرة فعلًا أقصر",
      "ارتفاع اللوحة صار يُحسب من المساحة الظاهرة فعلًا، فرأسها يبقى ظاهرًا وثابتًا دائمًا والمحتوى وحده يتمرّر تحته — مع خط خفيف أسفل الرأس يظهر أثناء التمرير",
      "على الجوال صار للوحة التفاصيل ارتفاع ثابت، فأزرار التنقّل تبقى بنفس المكان تحت الإصبع عند الانتقال بين الاستفسارات بدل ما تتحرك مع اختلاف طول كل استفسار",
      "كل استفسار تنتقل له يفتح من أعلاه، بدل ما يحتفظ بموضع التمرير من الاستفسار السابق",
      "وسوم رأس اللوحة (الأولوية، الفئة، جديد، مهم) تنكسر لسطر ثانٍ عند ضيق الشاشة بدل ما تدفع زر الإغلاق وأزرار التنقّل خارج اللوحة — كانت تحصل بالجوالات الأضيق",
      "نفس معالجة الارتفاع تشمل بقية النوافذ (سجل الإصدارات، الإشعارات، والإقرار القانوني)، مع منع تسرّب التمرير من اللوحة للصفحة الخلفية",
    ],
    en: [
      "Fixed: on phones (especially iPhone Safari) the inquiry detail sheet's header — the close button and previous/next buttons — slid above the top edge of the screen on long inquiries, because the sheet's height was computed from the screen height with the browser bars hidden, while the actually visible area is shorter",
      "The sheet's height now comes from the actually visible area, so its header always stays visible and fixed while only the content scrolls beneath it — with a subtle line under the header while scrolling",
      "On phones the detail sheet now has a fixed height, so the navigation buttons stay in the same spot under your finger when moving between inquiries instead of shifting with each inquiry's length",
      "Every inquiry you move to opens from its top instead of keeping the previous inquiry's scroll position",
      "The header tags (priority, category, New, Important) wrap onto a second line on narrow screens instead of pushing the close and navigation buttons out of the sheet — this happened on narrower phones",
      "The same height handling covers the other dialogs (update log, notices, and the legal notice), and scrolling inside a sheet no longer leaks to the page behind it",
    ],
  },
  {
    version: "2.8.1",
    dateAr: "9 سبتمبر 2026",
    dateEn: "September 9, 2026",
    ar: [
      "تصحيح: الموقع كان يفتح بالتصميم الكلاسيكي القديم ثم يقلب للتصميم المعتمد بعد ثانية تقريبًا — لأن التصميم والطقم يُقرآن من قاعدة البيانات، والموقع كان يرسم الافتراضي وهو ينتظر الرد",
      "صار التصميم والطقم المعتمدان يُحفظان بمتصفح الزائر ويُقرآن فورًا عند أول رسمة، فالزيارة المتكرّرة تفتح بالتصميم الصحيح مباشرة بلا أي انتظار ولا تبديل",
      "أول زيارة (ولا معلومات محفوظة بعد) تبدأ بشاشة إقلاع بلون الطقم بدل رسم تصميم يتبدّل بعدين — والموقع يجيب بياناته تحتها بنفس اللحظة، فما تأخّر شيء",
      "لون خلفية الصفحة يُطبَّق قبل تحميل حزمة الجافاسكربت أصلًا، فانتهى الوميض الأبيض عند فتح الموقع بالوضع الليلي",
      "خط الطقم المعتمد يبدأ تحميله من أول لحظة كذلك، فما يتبدّل شكل الخط تحت عين الزائر بعد ظهور النص",
      "تغيير التصميم من لوحة الإدارة يبقى فوريًا لكل الزوّار كما هو — قاعدة البيانات هي المرجع دائمًا، والمحفوظ بالمتصفح يُصحَّح لحظة وصول الرد",
    ],
    en: [
      "Fixed: the site opened in the old Classic design and then flipped to the approved design about a second later — the design and palette are read from the database, and the site was painting the default while it waited for the reply",
      "The approved design and palette are now stored in the visitor's browser and read instantly on first paint, so a returning visitor opens straight into the correct design with no wait and no switch",
      "A first-ever visit (nothing stored yet) starts on a boot screen tinted with the palette's own background instead of painting a design that changes later — and the site loads its data underneath it at the same moment, so nothing is delayed",
      "The page background color is applied before the JavaScript bundle even loads, ending the white flash when opening the site in dark mode",
      "The approved palette's font also starts loading from the first moment, so the lettering no longer changes shape after the text appears",
      "Changing the design from the admin panel still reaches every visitor instantly — the database remains the source of truth, and the browser's stored copy is corrected the moment the reply arrives",
    ],
  },
  {
    version: "2.8.0",
    dateAr: "9 سبتمبر 2026",
    dateEn: "September 9, 2026",
    ar: [
      "إعادة تصميم مخطط الفيلا التفاعلي (أين ظهرت الملاحظات) بشكل معماري: جدران بسماكة حقيقية، بروة فوق السطح، نوافذ وباب مدخل، درج بقلبات فعلية، وتهشير للجدار المتلاصق ومنسوب الأرض — بدل الكتل المصمتة السابقة",
      "توحيد تسميات مواقع الملاحظات (عمود «موقع الملاحظة») لتطابق تسميات مناطق المخطط حرفيًا، بما فيها الحوش الأمامي والحوش الخلفي والطبلون الكهربائي — عشان تنحسب كل ملاحظة بالمنطقة الصح بدون أي «غير محدد» زايدة",
    ],
    en: [
      "Redesigned the interactive villa plan (\"Where did the notes come from?\") with an architectural look: true-thickness walls, a roof parapet, windows and an entry door, real switchback stairs, and hatching for the party wall and ground level — replacing the previous solid-block shapes",
      "Standardized the note-location names (the \"Location\" column) to match the plan's zone labels exactly, including the front yard, back yard, and the electrical panel — so every note counts toward the correct zone with no extra \"unspecified\" entries",
    ],
  },
  {
    version: "2.7.0",
    dateAr: "9 سبتمبر 2026",
    dateEn: "September 9, 2026",
    ar: [
      "طريقة ثانية لتحديث تقدّم التنفيذ: إدخال مباشر بالموقع بدل ملف إكسل — تبديلة بأعلى لوحة الرفع بين \"ملف إكسل\" و\"إدخال مباشر بالموقع\"",
      "الإدخال المباشر يعرض الـ١٦ بلوك كحقول أرقام جاهزة، معبّاة تلقائيًا بآخر نسبة معروفة لكل بلوك (أو بنسبه الفعلية لو الشهر مسجَّل من قبل وتبي تصححه) — تعدّل بس اللي تغيّر وتترك الباقي",
      "تقدر تكتب نسبة مرحلة مباشرة من المطوّر أو تعلّم الشهر \"بلا قراءة\" من نفس النموذج",
      "نفس حماية النسخة الاحتياطية التلقائية قبل أي تحديث، بغض النظر عن الطريقة المستخدمة",
      "الطريقتان (ملف إكسل / إدخال مباشر) تكتبان لنفس الجداول بالضبط، فتقدر تبدّل بينهما شهر بشهر حسب الأسهل وقتها",
    ],
    en: [
      "A second way to update execution progress: direct entry on the site instead of an Excel file — a toggle at the top of the upload panel switches between \"Excel file\" and \"Direct entry on the site\"",
      "Direct entry shows all 16 blocks as ready number fields, pre-filled with each block's last known figure (or its actual figures if that month is already recorded and you're correcting it) — you only edit what changed and leave the rest",
      "You can also type a direct phase figure from the developer or mark the month as \"No reading\" from the same form",
      "Same automatic pre-update backup protection, regardless of which method is used",
      "Both methods (Excel file / direct entry) write to the exact same tables, so you can switch between them month to month depending on what's easiest at the time",
    ],
  },
  {
    version: "2.6.1",
    dateAr: "9 سبتمبر 2026",
    dateEn: "September 9, 2026",
    ar: [
      "زر \"تنزيل الملف الحالي\" صار يضيف تلقائيًا سطور الشهر القادم فاضية بآخر الملف (١٦ بلوك + ٤ مراحل اختيارية) — نفس الملف تنزّله، تعبّي الأرقام مباشرة، وترفعه، بدون تفكير بمكان الإضافة كل مرة",
      "سطور النموذج الفاضية غير المستخدمة (بلوك أو مرحلة موجودة بس الشهر والنسبة فاضيين) تُتجاوز بصمت عند الرفع بدل ما تظهر كخطأ — ما تحتاج تحذفها يدويًا لو ما احتجتها",
    ],
    en: [
      "The \"Download current file\" button now automatically appends blank next-month rows at the end of the file (16 blocks + 4 optional phases) — download, type the numbers straight in, upload, with no need to figure out where to add them each time",
      "Unused blank template rows (a block or phase filled in but month and percentage left empty) are now silently skipped on upload instead of surfacing as an error — no need to manually delete the ones you don't need",
    ],
  },
  {
    version: "2.6.0",
    dateAr: "9 سبتمبر 2026",
    dateEn: "September 9, 2026",
    ar: [
      "نسبة أي مرحلة ممكن تُدخَل الآن كرقم مباشر من المطوّر (سطر بالملف باسم المرحلة بدل رقم بلوك) بدل الاكتفاء بمتوسط بلوكاتها المرصودة — بعض المراحل تشمل بنودًا مثل \"الخدمات الأرضية\" غير مرصودة كبلوك مستقل، فرقم المطوّر أحيانًا يختلف عن المتوسط",
      "الرقم المباشر لو موجود يُستخدم لتلك المرحلة/الشهر بالذات فقط؛ الأشهر الثانية وبقية المراحل تبقى محسوبة من متوسط البلوكات كالمعتاد",
      "الإجمالي العام للمشروع صار = متوسط قيم المراحل الأربع الفعلية (بعد أي رقم مباشر)، بدل متوسط كل البلوكات الـ١٦ مباشرة — قرار مقصود لأن عدد البلوكات يختلف بين المراحل، وهذا غيّر أرقام الإجمالي المعروضة لكل الأشهر السابقة قليلًا (تصحيح لا خطأ)",
      "لوحة الرفع تعرض نسب المراحل المباشرة المكتشفة بالملف كقسم مستقل قبل التحديث (جديد/تغيّر عن آخر رقم مسجَّل)",
      "زر \"تنزيل الملف الحالي\" يُصدِّر هذي النسب المباشرة أيضًا، فيبقى الملف مرجعًا كاملًا يحكي القصة وحده",
    ],
    en: [
      "Any phase's percentage can now be entered as a direct developer figure (a row in the file named for the phase instead of a block number) instead of relying only on the average of its tracked blocks — some phases include items like site infrastructure that aren't tracked as an independent block, so the developer's number sometimes differs from that average",
      "A direct figure, when present, is used for that specific phase/month only; other months and other phases keep computing from the block average as before",
      "The project's overall total is now the average of the four actual phase values (after any direct figures), instead of a flat average of all 16 blocks — a deliberate choice since phases don't have equal block counts, and this slightly shifted the displayed total for every past month (a correction, not a bug)",
      "The upload panel shows detected direct phase figures as a separate section before applying (new / changed from the last recorded figure)",
      "The \"Download current file\" button now exports these direct phase figures too, so the file alone remains a complete reference",
    ],
  },
  {
    version: "2.5.0",
    dateAr: "9 سبتمبر 2026",
    dateEn: "September 9, 2026",
    ar: [
      "ملف بيانات التقدّم صار مرجعًا متصلًا بلا فجوات صامتة — شهر بلا قراءة من المطوّر يُسجَّل بسطر صريح واحد (\"لا قراءة\" + سبب مختصر) بدل ما يختفي من الملف",
      "زر \"تنزيل الملف الحالي\" يُصدِّر الآن كل التاريخ متضمّنًا أسطر \"لا قراءة\" هذي، فيبقى الملف نفسه دليلًا كاملًا يحكي القصة وحده",
      "لوحة الرفع تعرض أشهر \"لا قراءة\" المكتشفة بالملف كقسم مستقل قبل التحديث، وتحفظها بجدول جديد (progress_month_notes)",
      "تبويب \"تقدّم التنفيذ\" العام يعرض السبب الفعلي عند تمرير المؤشر على شهر باهت (بدل نص عام واحد لكل الحالات)، مع ملاحظة تفصيلية أسفل شريط الأشهر عند اختيار ذاك الشهر",
      "تصحيح: الملاحظة التوضيحية عن الأشهر الباهتة كانت تظهر فقط للأشهر الممتدة تلقائيًا حتى تاريخ اليوم، وما تظهر لفجوة داخل تاريخ مسجَّل فعليًا (مثل يوليو ٢٠٢٦) — صارت تظهر بالحالتين",
      "تسجيل الفجوة الحقيقية المعروفة حاليًا (يوليو ٢٠٢٦ — سحب المطوّر تقريره) بقاعدة البيانات، فتظهر بنصّها الفعلي من أول تحميل للموقع",
    ],
    en: [
      "The progress-data file is now a continuous reference with no silent gaps — a month with no developer reading gets one explicit row (\"No reading\" + a short reason) instead of simply vanishing from the file",
      "The \"Download current file\" button now exports the full history including these \"No reading\" rows, so the file alone tells the whole story",
      "The upload panel shows detected \"No reading\" months as a separate section before applying, and saves them to a new table (progress_month_notes)",
      "The public Execution Progress tab now shows the actual reason on hover for a faded month (instead of one generic line for every case), plus a detailed note under the month bar when that month is selected",
      "Fixed: the explanatory note about faded months only appeared for months auto-extended up to today, not for a gap inside already-recorded history (such as July 2026) — it now appears in both cases",
      "Recorded the one currently known real gap (July 2026 — developer withdrew that month's report) in the database, so it shows its actual reason from the first page load",
    ],
  },
  {
    version: "2.4.1",
    dateAr: "9 سبتمبر 2026",
    dateEn: "September 9, 2026",
    ar: [
      "حذف آخر بقايا كود غير متصلة بقاعدة البيانات: مسار قراءة قديم لبيانات الاستفسارات كان يعتمد على window.storage (واجهة بيئة المعاينة فقط) ولا يعمل شيئًا فعليًا بعد النشر على Vercel — بيانات الاستفسارات دائمًا كانت تُقرأ من Supabase مباشرة عبر مسار آخر، وهذا كان مجرد كود ميت لا يفعل شيئاً",
      "تبسيط حفظ تفضيلات الزائر (الوضع الليلي/الفاتح واللغة) إلى localStorage وحدها — كانت تحاول الكتابة لـ window.storage أيضًا بلا أي فائدة فعلية",
      "كل بيانات المشروع الآن مصدرها الوحيد قاعدة البيانات مباشرة: الاستفسارات (inquiries)، وتقدّم التنفيذ (progress_readings/progress_blocks)، والإعدادات والفلاتر والوثائق — لا يوجد أي مسار بديل أو مخبّأ محليًا",
    ],
    en: [
      "Removed the last piece of code not actually connected to the database: an old inquiries-loading path relied on window.storage (a preview-environment-only API) and did nothing once deployed to Vercel — inquiry data was always being read from Supabase through a separate path regardless, so this was simply dead code doing nothing",
      "Simplified visitor preference storage (light/dark mode and language) to localStorage only — it was also attempting a pointless write to window.storage",
      "Every piece of project data now has a single source of truth in the database: inquiries, execution progress (progress_readings/progress_blocks), settings, filters, and documents — no alternate or locally-cached path remains",
    ],
  },
  {
    version: "2.4.0",
    dateAr: "9 سبتمبر 2026",
    dateEn: "September 9, 2026",
    ar: [
      "إعادة بناء كاملة لنظام تقدّم التنفيذ من الصفر — ملف الرفع، القارئ، وقاعدة البيانات",
      "ملف الرفع صار بتنسيق مسطّح بسيط: عمود لكل من رقم البلوك / الشهر / نسبة الإنجاز، صف واحد لكل بلوك بكل شهر — بدل جدول عريض بأعمدة أشهر متحركة كان يحتاج تأكيد سنة أول عمود يدويًا",
      "الإجمالي ومتوسط كل مرحلة ما يُدخَلان ولا يُقرآن من الملف بعد الآن — قاعدة البيانات تحسبهم دائمًا آليًا من أرقام البلوكات نفسها، فيستحيل يتناقضا مع بعض بالتصميم",
      "هذا التغيير صحّح تناقضًا كان موجودًا فعليًا ببيانات أغسطس ٢٠٢٦ المنشورة: رقم الإجمالي المخزَّن ما كان يطابق متوسط البلوكات الفعلي لنفس الشهر",
      "زر جديد \"تنزيل الملف الحالي\" بلوحة الرفع — ينزّل كل التاريخ المسجَّل بنفس تنسيق الرفع، جاهز لإضافة سطور الشهر الجديد بأسفله وإعادة رفعه",
      "بلوك جديد بالمشروع يُسجَّل من نفس لوحة الرفع (رقمه ومرحلته) وقت وروده بالملف، بدل ما يُصنَّف تلقائيًا \"غير مصنّف\" بالكود",
      "معاينة الرفع صارت بدقّة بلوك واحد لكل شهر (جديد/تغيّر/بدون تغيير)، بدل ملخّص شهر كامل فقط",
      "حماية فقدان البيانات انتقلت لنفس الدقة: شهر تُستبعد بلوكاته الناقصة تلقائيًا ويحتاج تأكيدًا صريحًا، بدل استبعاد الشهر كاملًا",
      "رسائل الأخطاء تشير لعنوان الخلية بالملف (مثل \"C42\") مباشرة",
      "حُذف جدول progress_matrix القديم نهائيًا بعد ترحيل كل بياناته التاريخية بنجاح لهذا النظام الجديد",
    ],
    en: [
      "Full rebuild of the execution-progress system from the ground up — upload file, reader, and database",
      "The upload file is now a simple flat format: one column each for block number / month / progress percentage, one row per block per month — replacing a wide table with shifting month columns that needed manual confirmation of the first column's year",
      "The total and each phase's average are no longer entered into or read from the file — the database always computes them live from the block figures themselves, making them structurally impossible to contradict each other",
      "This change fixed a real contradiction that was live in the published August 2026 data: the stored total did not match the actual average of that month's blocks",
      "New \"Download current file\" button in the upload panel — exports the full recorded history in the same upload format, ready to append the new month's rows and re-upload",
      "A new project block is registered (its number and phase) from the same upload panel the moment it appears in a file, instead of falling back to an \"unclassified\" bucket in the code",
      "Upload preview is now accurate to a single block per month (new/changed/unchanged), instead of only a whole-month summary",
      "Data-loss protection moved to the same precision: a month with missing blocks has just those blocks excluded automatically and needs explicit confirmation, instead of excluding the whole month",
      "Error messages point at the file's cell address (such as \"C42\") directly",
      "The old progress_matrix table was permanently dropped after all its historical data was successfully migrated to this new system",
    ],
  },
  {
    version: "2.3.0",
    dateAr: "8 سبتمبر 2026",
    dateEn: "September 8, 2026",
    ar: [
      "مدقّق ملف الاستفسارات صار محليًا بالكامل: بلا إنترنت ولا خدمة خارجية، ونفس الملف يعطي نفس النتيجة دائمًا",
      "خريطة ربط الأعمدة: كل عمود بالملف ووين انربط — والأهم أنها تكشف أي عمود فيه بيانات كان يُهمل بصمت",
      "الملاحظة صارت تشير لعنوان الخلية بإكسل (مثل «H53») بدل رقم البند فقط، فتفتح الملف وتصلح مباشرة",
      "كشف إزاحة الصفوف: لو الملف مزاح صفًا فكل بند يحمل نص بند مجاور — يُرصد قبل ما يستبدل بيانات صحيحة ببيانات بند ثاني",
      "كشف انزياح التوزيع: انقلاب مفاجئ بنسب الحالة أو الفئة مؤشر على عمود بمكان غلط",
      "تحذير عند الحذف الجماعي: ملف يغطي أقل من نصف السجل غالبًا شيت جزئي مو قرار حذف",
      "تعريف الأعمدة: خلية نصية داخل عمود كله أرقام تُرصد، وتعدّد صيغ التاريخ بعمود الشهر يُنبّه له",
      "قياس على سجلك أنت: ملاحظة أقصر أو أطول بكثير من المعتاد، وتركيبة نموذج وموقع ما ظهرت من قبل",
      "خلايا أخطاء إكسل (‏#REF!‎ وأمثالها) تُرصد بموقعها بدل ما تدخل السجل كنص",
      "أربعة مستويات للملاحظات، وتقرير تدقيق كامل تنسخه أو تنزّله",
      "مستوى «أوقف واقرأ» يُعرض بوضوح لكنه ما يمنع الاعتماد — القرار يبقى لك",
    ],
    en: [
      "The inquiry file auditor is now fully local: no internet, no external service, and the same file always yields the same result",
      "A column mapping view: every column in the file and where it landed — and, most importantly, it exposes any column holding data that was being silently dropped",
      "Findings now point at the Excel cell address (such as H53) rather than just the item number, so you can open the file and fix it directly",
      "Row-shift detection: if the file is off by one row, every item carries its neighbour's text — caught before it overwrites correct data with another item's",
      "Distribution-shift detection: a sudden flip in status or category proportions signals a column in the wrong place",
      "A mass-deletion warning: a file covering less than half the record is usually a partial sheet, not a decision to delete",
      "Column profiling: a text cell inside an all-numeric column is flagged, and mixed date formats in the month column raise a warning",
      "Measured against your own record: notes far shorter or longer than usual, and model/location pairings never seen before",
      "Excel error cells (#REF! and the like) are caught with their location instead of entering the record as text",
      "Four finding levels, plus a full audit report you can copy or download",
      "The stop-and-read level is shown clearly but never blocks the import — the decision stays yours",
    ],
  },
  {
    version: "2.2.0",
    dateAr: "8 سبتمبر 2026",
    dateEn: "September 8, 2026",
    ar: [
      "قارئ ملف الاستفسارات صار ينظّف الملف قبل أي مقارنة: مسافات ورموز اتجاه مخفية، أرقام عربية، وصيغ «نعم/لا» المتعددة",
      "توحيد إملاء القيم على الصيغة المعتمدة — «معتمده» تُحفظ «معتمدة»، فما تتراكم صيغ متعددة لنفس القيمة وتكسر الفلاتر",
      "المقارنة صارت تتجاهل الفروق الشكلية: صف ما يظهر «معدّلًا» لمجرد مسافة أو همزة أو علامة ترقيم",
      "تدقيق تلقائي للملف المرفوع: تناقض بين الإغلاق والحالة، حالة محسومة بلا رد، رقم مكرر، وقيم خارج القائمة المعتمدة مع اقتراح أقرب قيمة صحيحة",
      "كشف الصفوف المكرّرة بالمعنى لا بالرقم — نفس الملاحظة بصياغة مختلفة تُرفع للمراجعة",
      "تحذير حرج لما يفرّغ الملف حقلًا معبّأً حاليًا، لأن الغالب شيت ناقص مو حذفًا مقصودًا",
      "كشف رجوع الحالة للخلف (من محسومة إلى قيد الدراسة) وتغيّر نص الملاحظة جذريًا على نفس الرقم",
      "ملخّص عربي لكل مزامنة: كم إضافة وكم تعديل وأكثر الحقول تغيّرًا",
      "مراجعة ذكية اختيارية فوق الفحوصات المحلية — وإذا كانت مقطوعة يظل التدقيق شغّالًا كما هو",
      "الترجمة للإنجليزية صارت دفعة واحدة بدل صف صف، فالمزامنة الكبيرة تخلص أسرع بكثير",
      "زر «ملخص» انتقل من ترويسة الموقع إلى لوحة الإدارة وتوسّع — الزائر ما كان يحتاجه",
      "إصلاحات أمنية بقاعدة البيانات: سدّ تصعيد الصلاحيات، إقفال دوال حساسة كانت مكشوفة، ومنع بيانات داخلية من الوصول للزوار",
    ],
    en: [
      "The inquiry import now cleans the file before any comparison: stray spaces, hidden direction marks, Arabic-Indic digits, and the many spellings of yes/no",
      "Values are snapped to their approved spelling, so variants of the same value stop accumulating and breaking the filters",
      "Comparison now ignores cosmetic differences — a row no longer reads as changed over a space, a hamza, or a punctuation mark",
      "Automatic auditing of the uploaded file: closed/status contradictions, decided items with no reply, duplicate ids, and values outside the approved list with the nearest valid one suggested",
      "Near-duplicate detection by meaning rather than by id — the same note reworded is raised for review",
      "A critical warning when the file would blank a field that currently holds data, since that usually means a partial sheet rather than an intentional deletion",
      "Detection of status moving backwards (decided back to under review) and of a note changing wholesale under the same id",
      "An Arabic digest for every sync: how many additions, how many edits, and which fields changed most",
      "Optional AI review layered on top of the local checks — if it is unavailable the auditing carries on unchanged",
      "English translation now runs in batches instead of row by row, so large syncs finish far faster",
      "The Summary button moved from the site header into the admin panel and grew — visitors did not need it",
      "Database security fixes: privilege escalation closed, sensitive functions locked down, and internal data kept away from visitors",
    ],
  },
  {
    version: "2.1.0",
    dateAr: "8 سبتمبر 2026",
    dateEn: "September 8, 2026",
    ar: [
      "إصلاح: نافذة الإقرار كانت تنزل بأعلى الصفحة بدل ما تكون فوق المحتوى — رجعت نافذة مستقلة بالنص، وزر «أوافق» ظهر واضحًا بعد ما كان أبيض على أبيض",
      "الإقرار صار بخانة قائمة بذاتها: رأس ملوّن، وكل بند داخل صندوق مستقل، وتذييل ثابت يحمل زر الموافقة",
      "إعادة ترتيب «نظرة عامة»: عمودان على الشاشات الكبيرة — «أحدث الملاحظات» و«طبيعة البنود» جنب بعض بدل ما تكون تحت بعض",
      "«حالة السجل» صارت بعمودين: العنوان والرقم على جهة، وشريط التوزيع ومفاتيح الحالة على الجهة الثانية",
      "مفاتيح الحالة صارت بلاطات مستقلة بحدود، بدل صفوف مسطحة",
      "الترويسة صارت لوحة بارزة بحد خفيف وهالة لونية، وأزرار الأدوات تجمّعت داخل حبّة زجاجية",
      "«أحدث الملاحظات» صارت خطًا زمنيًا بعمود وعُقد بدل قائمة عادية",
      "ثلاثة أعمدة للبطاقات على الشاشات العريضة جدًا، وعمودان لقائمة المخططات",
      "عرض الصفحة اتّسع من 1120 إلى 1240 بكسل للاستفادة من الشاشات الكبيرة",
    ],
    en: [
      "Fix: the disclaimer was dropping into the top of the page instead of floating above it — it is a standalone centred dialog again, and the Agree button is visible after rendering white-on-white",
      "The disclaimer now stands on its own: a tinted header, each clause in its own box, and a fixed footer holding the agree button",
      "Overview reorganised: two columns on large screens — Latest Notes and Item Categories now sit side by side instead of stacked",
      "Record Status is now a two-column panel: heading and total on one side, distribution bar and status keys on the other",
      "Status keys are now bordered tiles instead of flat rows",
      "The header is a raised panel with a hairline edge and a colour bloom; toolbar buttons are grouped inside a glass pill",
      "Latest Notes is now a timeline with a spine and nodes instead of a plain list",
      "Three-column cards on very wide screens, and a two-column document list",
      "Page width widened from 1120 to 1240px to make use of large screens",
    ],
  },
  {
    version: "2.0.0",
    dateAr: "8 سبتمبر 2026",
    dateEn: "September 8, 2026",
    ar: [
      "تصميم جديد كليًا باسم «نوفا» — ألواح زجاجية شفافة، خلفية شفقية متحركة، وحبيبات ناعمة تكسر تدرّج الألوان",
      "ظهور تدريجي للأقسام مع التمرير، ودخول متتابع للبطاقات واحدة بعد الأخرى",
      "إضاءة تتبع مؤشر الفأرة داخل البطاقات، ولمعة تمر على الأزرار عند التحويم (أجهزة سطح المكتب)",
      "شريط التبويبات صار حبّة عائمة زجاجية، والتبويب النشط بتدرّج لوني بدل الخط السفلي",
      "الرقم الإجمالي وعنوان الصفحة بتدرّج لوني، وأشرطة الحالة فيها لمعة متحركة",
      "مفتاح تبديل التصميم بلوحة الإدارة: «الكلاسيكي» أو «نوفا» — التبديل ينتقل لكل الزوّار فورًا بدون إعادة نشر",
      "التصميم مستقل عن طقم الألوان: أي طقم من الخمسة يشتغل مع أي تصميم من الاثنين",
      "التصميم القديم باقٍ كما هو حرفيًا — الرجوع له بضغطة واحدة",
      "احترام كامل لإعداد «تقليل الحركة» بالجهاز: كل التأثيرات تنطفئ تلقائيًا",
    ],
    en: [
      "A brand-new design called Nova — translucent glass panels, a drifting aurora backdrop, and fine grain to break up the gradients",
      "Sections fade and rise into view as you scroll, with cards entering one after another",
      "Cursor-tracking light inside cards and a shine sweeping across buttons on hover (desktop)",
      "The tab bar is now a floating glass pill, with the active tab filled by a gradient instead of an underline",
      "Gradient treatment on the headline and the total count, plus an animated sheen across the status bars",
      "A design switch in the admin panel: Classic or Nova — the change reaches every visitor instantly, with no redeploy",
      "Design and colour set are independent: any of the five sets works with either design",
      "The old design is preserved exactly as it was — one click to go back",
      "Full respect for the device's reduce-motion setting: every effect switches off automatically",
    ],
  },
  {
    version: "1.18.0",
    dateAr: "7 سبتمبر 2026",
    dateEn: "September 7, 2026",
    ar: [
      "مظهر خامس: «المسار» — ترتيب زمني بدل القائمة المسطحة؛ عمود فقري يمتد على طول الصفحة تتفرّع منه القيود بعُقد وخطوط وصل",
      "لون الطين الدافئ على خلفية خضراء داكنة — لوحة لون لم تُستخدم في أي مظهر سابق",
      "المظاهر الأربعة السابقة باقية كما هي، والاختيار بينها كلها من تبويب «مظهر الموقع»",
    ],
    en: [
      "A fifth look: Masar — a chronological arrangement instead of a flat list; a spine runs down the page with entries branching off it via nodes and connector lines",
      "Warm clay on deep green — a palette used in none of the earlier looks",
      "The four earlier looks are unchanged, and all five are selectable from the site appearance tab",
    ],
  },
  {
    version: "1.17.0",
    dateAr: "7 سبتمبر 2026",
    dateEn: "September 7, 2026",
    ar: [
      "مظهر رابع: «المُخطَّط» — مبني على لغة الرسم التنفيذي، بورق شبكة وعلامات زوايا وخطوط أبعاد، ومقابض تحديد تظهر عند المرور على أي بند",
      "الأولوية العالية تُعلَّم باللون الأحمر الاصطلاحي للتأشير على المخططات",
      "المظاهر الثلاثة السابقة باقية كما هي، والاختيار بينها كلها من تبويب «مظهر الموقع»",
    ],
    en: [
      "A fourth look: Mukhattat — built on architectural drafting language, with grid paper, corner ticks, dimension lines, and selection handles that appear on hover",
      "High priority is marked in the red conventionally used for drawing markup",
      "The three earlier looks are unchanged, and all four are selectable from the site appearance tab",
    ],
  },
  {
    version: "1.16.1",
    dateAr: "7 سبتمبر 2026",
    dateEn: "September 7, 2026",
    ar: [
      "إصلاح عاجل: النوافذ المنبثقة (الإقرار القانوني، الإشعارات، تفاصيل الاستفسار، عارض المستندات) كانت تظهر مدمجة داخل الصفحة بدل أن تطفو فوقها بعد تحديث ١٫١٦٫٠ — رجعت لوضعها الصحيح",
      "أُصلح معها شريط تقدّم القراءة وزر الرجوع للأعلى",
    ],
    en: [
      "Hotfix: pop-up panels (legal notice, notices, inquiry details, document viewer) were rendering inline in the page instead of floating above it after 1.16.0 — now restored",
      "The reading-progress bar and the back-to-top button are fixed along with them",
    ],
  },
  {
    version: "1.16.0",
    dateAr: "7 سبتمبر 2026",
    dateEn: "September 7, 2026",
    ar: [
      "مظهر الموقع صار قابلاً للتبديل من لوحة الإدارة: ثلاثة أطقم — الكلاسيكي، «أُفق»، و«المَحضر» — والاعتماد ينتقل لكل الزوّار فورًا بدون إعادة نشر",
      "«أُفق»: كحلي معماري ونحاسي دافئ، ألواح زجاجية وخلفية شفق متحرك",
      "«المَحضر»: هوية أرشيفية رسمية بخط نسخي للعناوين وخطوط شعرة ونحاسي مكسور",
      "كل طقم فيه نسخة نهارية وليلية تتبع إعداد جهاز الزائر تلقائيًا",
    ],
    en: [
      "The public site's look can now be switched from the admin panel: three sets — Classic, Ufuq, and Mahdar — and the choice reaches every visitor instantly with no redeploy",
      "Ufuq: architectural navy with warm brass, glass panels and a drifting aurora backdrop",
      "Mahdar: a formal archival identity with a naskh serif for headings, hairline rules and muted brass",
      "Each set ships light and dark variants that follow the visitor's device setting automatically",
    ],
  },
  {
    version: "1.15.0",
    dateAr: "7 سبتمبر 2026",
    dateEn: "September 7, 2026",
    ar: [
      "اختياراتك صارت تُحفظ فعليًا: الوضع الليلي/النهاري، اللغة، وشكل العرض (بطاقات أو جدول) تبقى كما تركتها عند كل زيارة بدل أن ترجع للافتراضي",
      "إصلاح عطل كان يوقف رفع ملف \"تقدّم الوحدة والمراحل\" في خطوته الأخيرة",
      "إصلاح عطل بلوحة الإدارة عند اختيار قرار لقيمة فلترة جديدة أثناء المزامنة",
      "استكمال الترجمة الإنجليزية لمواقع وجهات كانت تظهر بالعربية (منها \"الطابق الأرضي\" و\"م/أحمد ملحم\")، مع مطابقة تتحمّل اختلاف الإملاء",
      "ضبط لغة واتجاه الصفحة تلقائيًا عند التبديل للإنجليزية — يخدم قارئات الشاشة",
      "تحسين سرعة تبويب الزيارات والتحليلات، وتنسيق صناديق التنبيه بلوحة الرفع",
    ],
    en: [
      "Your choices now actually persist: light/dark mode, language, and view style (cards or table) stay as you left them on every visit instead of resetting",
      "Fixed a crash that stopped the \"unit & phase progress\" upload at its final step",
      "Fixed a crash in the admin panel when choosing a decision for a new filter value during sync",
      "Completed English translations for locations and owners that were still showing in Arabic (including \"Ground Floor\" and \"Eng. Ahmed Malham\"), with spelling-tolerant matching",
      "Page language and direction now switch automatically in English mode — helps screen readers",
      "Faster analytics tab, and properly styled alert boxes in the upload panel",
    ],
  },
  {
    version: "1.14.0",
    dateAr: "3 سبتمبر 2026",
    dateEn: "September 3, 2026",
    ar: [
      "فرز جديد بقائمة الاستفسارات في لوحة الإدارة: \"تاريخ الرد\" — يرتّب حسب تاريخ الرد الخاص بالاستفسار نفسه، الأحدث فوق، وصار هو الترتيب الافتراضي",
      "الاستفسارات التي لم يصدر بشأنها رد بعد تنزل آخر القائمة بدل أن تتصدّرها، ويظهر بجانبها \"بانتظار الرد\"",
      "عند تساوي شهر الرد، يُرتَّب الأحدث إضافة أولاً",
    ],
    en: [
      "New sort in the admin inquiries list: \"Reply date\" — orders by the inquiry's own reply date, newest first, and is now the default",
      "Inquiries with no reply yet drop to the bottom instead of leading the list, and are labelled \"awaiting reply\"",
      "Ties within the same reply month are ordered by newest added first",
    ],
  },
  {
    version: "1.13.1",
    dateAr: "2 سبتمبر 2026",
    dateEn: "September 2, 2026",
    ar: [
      "إصلاح: كان الرسم البياني \"مسار الردود والتراكم\" يظهر فاضيًا — السبب أن عمود شهر الرد انمسح من قاعدة البيانات بالكامل أثناء رفع سابق. تم استرجاع القيم وإصلاح سبب المسح",
      "إصلاح جوهري بالتدقيق: كان الرفع يُبلّغ عن \"تعديل\" على كل الاستفسارات في كل مرة. الآن تُوحَّد القيم قبل المقارنة (مسافات زائدة، همزات، تشكيل، أرقام عربية-هندية، وصيغ التواريخ)، فما يُعرض إلا التغيير الحقيقي فعلًا",
      "حماية جديدة: خلية فاضية بالملف المرفوع ما تعود تمسح قيمة موجودة — تُعامَل كـ\"ما فيه بيانات\" بدل \"احذف\". هذي هي الثغرة التي مسحت عمود الشهر",
      "قراءة أذكى لعمود الشهر: يقبل التاريخ بأي صيغة ويحوّله لـ YYYY-MM، ولا يسمح لعمود المعادلة الفاضي بطمس عمود التاريخ الصحيح",
    ],
    en: [
      "Fix: the \"Reply Trend & Cumulative\" chart was rendering empty — the reply-month column had been wiped from the database entirely during an earlier import. Values restored and the underlying cause fixed",
      "Major diff fix: every import was reporting a change on every single inquiry. Values are now normalized before comparison (extra spaces, hamza forms, diacritics, Arabic-Indic digits, and date formats), so only genuine changes are shown",
      "New safeguard: a blank cell in an uploaded file no longer clears an existing value — it is treated as \"no data\" rather than \"delete\". This was the exact gap that wiped the month column",
      "Smarter month parsing: accepts dates in any format and converts them to YYYY-MM, and no longer lets an empty formula column overwrite a valid date column",
    ],
  },
  {
    version: "1.13.0",
    dateAr: "2 سبتمبر 2026",
    dateEn: "September 2, 2026",
    ar: [
      "فلتر جديد: \"الاجتماع الخامس\" — يعرض البنود التي صدر بشأنها رد في اجتماع 2 سبتمبر 2026 (٩ بنود)",
      "فلاتر الاجتماعات صارت تطابق كل اجتماع مرتبط بالبند، مو أول اجتماع فقط — قبل كذا كان البند المرتبط بأكثر من اجتماع يختفي من فلاتر الاجتماعات السابقة",
      "إضافة عدّاد بجانب اسم كل اجتماع يوضح عدد بنوده",
      "تحديث ردود وحالات ٩ بنود (٣٠، ٥٣، ٦٦، ٧٦، ٨٠، ٨١، ٨٢، ٨٤، ٨٥) — أُقفلت منها ٥ بنود",
    ],
    en: [
      "New filter: \"5th Meeting\" — shows the items answered in the September 2, 2026 meeting (9 items)",
      "Meeting filters now match every meeting an item is linked to, not just the first one — previously an item linked to several meetings disappeared from the earlier meetings' filters",
      "Added a per-meeting item count next to each meeting name",
      "Updated replies and statuses for 9 items (30, 53, 66, 76, 80, 81, 82, 84, 85) — 5 of them were closed",
    ],
  },
  {
    version: "1.12.3",
    dateAr: "30 أغسطس 2026",
    dateEn: "August 30, 2026",
    ar: ["تعويض تلقائي لخلية \"الإجمالي\" الفاضية بجدول المراحل: لو المراحل الأربعة معبّاة لشهر معيّن لكن خليته \"الإجمالي\" فاضية (يصير هذا لما تتعدَّل خلايا المراحل يدويًا وتنكسر الصيغة المرتبطة بالإجمالي)، يُحسب الإجمالي تلقائيًا كمتوسط المراحل الأربعة — نفس الأسلوب الموثّق فعليًا بملاحظات الملف. اكتُشفت هذي الحالة الحقيقية بعد فحص ملف معدَّل فعليًا أرسله المستخدم"],
    en: ["Automatic fallback for a blank \"Total\" cell in the phases table: if all four phases have values for a given month but the Total cell is blank (this happens when the phase cells are edited by hand and the formula feeding Total breaks), the total is now computed automatically as the average of the four phases — matching the methodology already documented in the file's own notes. This real scenario was discovered after reviewing an actually-edited file the user sent"],
  },
  {
    version: "1.12.2",
    dateAr: "30 أغسطس 2026",
    dateEn: "August 30, 2026",
    ar: ["إصلاح جذري لقراءة جدول المراحل بملف تقدّم الوحدة: صار كل صف (الإجمالي، والمراحل ١-٤) يُكتشف بمطابقة نصّه هو نفسه، بدل الاعتماد على عدّ عدد صفوف ثابت من عنوان الجدول — هذا هو سبب رجوع أرقام غلط لبعض المراحل ومسح شهور فبراير-يونيو بالرفعة الأولى الفعلية. جدول البلوكات ما تأثر لأنه أصلًا مبني على نفس مبدأ المطابقة بالمحتوى"],
    en: ["Root-cause fix for reading the phases table in the unit-progress file: every row (Total, and Phases 1-4) is now located by matching its own text, instead of counting a fixed number of rows down from the table title — this was the actual cause of the wrong phase numbers and the wiped February-June months on the real first upload. The blocks table was unaffected since it already worked on content-matching"],
  },
  {
    version: "1.12.1",
    dateAr: "30 أغسطس 2026",
    dateEn: "August 30, 2026",
    ar: ["إضافة حماية من فقدان البيانات برفع ملف تقدّم الوحدة: أي شهر يرجع بقيم أقل بكثير مما هو مسجَّل له فعلًا يُستبعد تلقائيًا من التحديث بدل الكتابة فوقه، ويحتاج تأكيدًا صريحًا لكل شهر منه لو كان مقصودًا. كذلك صار تعذّر التعرّف على صف \"إجمالي المشروع\" بشيت KPIs يوقف القراءة بخطأ واضح بدل المتابعة بأرقام قد تكون غلط"],
    en: ["Added data-loss protection to the unit-progress upload: any month whose parsed values are far fewer than what's already recorded is now automatically excluded from the update instead of overwriting it, and needs explicit per-month confirmation if truly intended. Also, failing to locate the \"Total Project\" row in the KPIs sheet now stops the read with a clear error instead of continuing with potentially wrong numbers"],
  },
  {
    version: "1.12.0",
    dateAr: "30 أغسطس 2026",
    dateEn: "August 30, 2026",
    ar: ["إضافة رفع تلقائي لملف \"تقدّم الوحدة والمراحل\" من لوحة الإدارة — يقرأ شيت KPIs بدون أي إعداد يدوي للأعمدة ويحدّث تبويب «تقدّم التنفيذ» بالموقع العام مباشرة لكل الزوّار عبر قاعدة البيانات، بدل الاعتماد على تعديل الكود وإعادة النشر كل شهر"],
    en: ["Added automatic upload for the \"Unit & Phases Progress\" file from the admin panel — reads the KPIs sheet with zero manual column setup and updates the public \"Execution Progress\" tab live for all visitors via the database, instead of relying on a code edit and redeploy each month"],
  },
  {
    version: "1.11.2",
    dateAr: "30 أغسطس 2026",
    dateEn: "August 30, 2026",
    ar: ["تحديث بيانات تقدّم التنفيذ حتى أغسطس 2026 — لا قراءة جديدة لشهر يوليو (يظهر باهتًا بهدف محسوب وإنجاز فارغ)، مطابقةً لملف «تقدّم الوحدة والمراحل» المحدَّث"],
    en: ["Updated execution-progress data through August 2026 — no new reading for July (shown faded with a computed target and empty actual progress), matching the updated \"Unit & Phases Progress\" file"],
  },
  {
    version: "1.11.1",
    dateAr: "29 أغسطس 2026",
    dateEn: "August 29, 2026",
    ar: ["إصلاحات"],
    en: ["Fixes"],
  },
  {
    version: "1.11.0",
    dateAr: "29 أغسطس 2026",
    dateEn: "August 29, 2026",
    ar: ["إصلاحات"],
    en: ["Fixes"],
  },
  {
    version: "1.10.3",
    dateAr: "29 أغسطس 2026",
    dateEn: "August 29, 2026",
    ar: ["إصلاحات"],
    en: ["Fixes"],
  },
  {
    version: "1.10.2",
    dateAr: "29 أغسطس 2026",
    dateEn: "August 29, 2026",
    ar: [
      "تصحيح خطأ حقيقي: علامتا \"يلزم الاطلاع\" و\"مهم\" ما كانتا تظهران على الموقع العام رغم تفعيلهما من لوحة الإدارة — السبب أن دالة قراءة البيانات الحيّة كانت تتجاهل هذين الحقلين تحديدًا قبل ما توصل للبطاقات. تم تصحيحها.",
    ],
    en: [
      "Fixed a real bug: the \"Needs review\" and \"Important\" marks never appeared on the public site even when enabled from the admin panel — the live-data mapping function was silently dropping exactly those two fields before they reached the cards. Corrected.",
    ],
  },
  {
    version: "1.10.0",
    dateAr: "29 أغسطس 2026",
    dateEn: "August 29, 2026",
    ar: [
      "علامة جديدة \"مهم\" — إطار أحمر واضح مع وميض لافت، أقوى من تأثير شارة \"جديد\"",
      "تظهر بالبطاقة والجدول ولوحة التفاصيل، وتُفعَّل/تُلغى يدويًا بالكامل من لوحة الإدارة بدون أي مدة انتهاء تلقائية (بخلاف \"جديد\" اللي ينتهي بعد ٧ أيام)",
      "فلتر مخصص \"مهم\" بلوحة المتابعة — يظهر فقط لو فيه استفسار واحد مفعّل عليه الوسم، ويختفي تلقائيًا لو ما فيه شي",
    ],
    en: [
      "New \"Important\" tag — a clear red border with an attention-grabbing blink, stronger than the existing \"New\" badge effect",
      "Shown on the card, table, and detail sheet; toggled fully manually from the admin panel with no auto-expiry (unlike \"New\", which expires after 7 days)",
      "Dedicated \"Important\" filter in the notes board — only appears when at least one inquiry is flagged, and disappears automatically when none are",
    ],
  },
  {
    version: "1.9.0",
    dateAr: "29 أغسطس 2026",
    dateEn: "August 29, 2026",
    ar: [
      "علامة مائية جديدة وواضحة \"يلزم الاطلاع\" تظهر على بطاقة أي استفسار تفعّله الإدارة — بلون تحذيري وشفافية أعلى بكثير من رقم الاستفسار الخافت",
      "تُفعَّل وتُلغى من لوحة الإدارة (زر النجمة بقائمة الاستفسارات) بنفس صلاحية وسم \"عاجل\" الحالية",
      "خيار فرز جديد بقائمة الاستفسارات بلوحة الإدارة: الأحدث تعديلاً، الأحدث إضافة، أو رقم الاستفسار — لتسهيل الوصول لآخر التعديلات",
      "كل استفسار بالقائمة يعرض الآن تاريخ آخر تعديل أو الإضافة بجانبه حسب الفرز المختار",
    ],
    en: [
      "New, clearly visible \"Needs review\" watermark on any inquiry card the admin flags — a warning color and far higher opacity than the faint inquiry-number mark",
      "Toggled on and off from the admin panel (the star button in the inquiries list), using the existing \"urgent\" permission",
      "New sort option in the admin inquiries list: most recently modified, most recently added, or inquiry number — to quickly reach the latest updates",
      "Each inquiry row now shows its last-modified or added date next to it, matching the chosen sort",
    ],
  },
  {
    version: "1.8.0",
    dateAr: "26 أغسطس 2026",
    dateEn: "August 26, 2026",
    ar: [
      "إضافة «فئة البند» لكل استفسار — تصحيح عيب تنفيذي، تصميمي/جمالي، ترقية، استفسار فني، تجاري، إداري",
      "الفئة تظهر كشارة ملوّنة عند كل استفسار بالبطاقات والجدول ولوحة التفاصيل",
      "فلتر جديد بالفئة مع عدّاد لكل فئة، وصار البحث النصي يشملها",
      "لوحة «طبيعة البنود» بالنظرة العامة — توزيع الاستفسارات على الفئات بضغطة واحدة",
    ],
    en: [
      "Added an item category to every inquiry — defect fix, design/aesthetic, upgrade, technical, commercial, administrative",
      "The category now shows as a colored badge on every inquiry in cards, table, and detail view",
      "New category filter with per-category counts; free-text search now covers it too",
      "New \"Item Categories\" panel in the overview showing how inquiries break down",
    ],
  },
  {
    version: "1.7.9",
    dateAr: "11 أغسطس 2026",
    dateEn: "August 11, 2026",
    ar: ["تحديث بيانات موقع لبندين", "تحديث بيانات مسؤول وشهر لبند"],
    en: ["Updated location data for two items", "Updated owner and month data for one item"],
  },
  {
    version: "1.7.8",
    dateAr: "11 أغسطس 2026",
    dateEn: "August 11, 2026",
    ar: ["ربط بنود بالاجتماع الرابع"],
    en: ["Linked items to the fourth meeting"],
  },
  {
    version: "1.7.7",
    dateAr: "11 أغسطس 2026",
    dateEn: "August 11, 2026",
    ar: ["إعادة هيكلة داخلية لتخزين بيانات الاستفسارات (بدون تغيير مرئي)"],
    en: ["Internal restructuring of inquiry data storage (no visual change)"],
  },
  {
    version: "1.7.6",
    dateAr: "10 أغسطس 2026",
    dateEn: "August 10, 2026",
    ar: [
      "عارض مخططات جديد بملء الشاشة مع تكبير بالإصبعين أو بنقرتين",
      "تقسيم كل مخطط إلى لوحات مسمّاة: الأدوار، الواجهات، القطاعات",
      "بطاقات المخططات صارت بصور مصغّرة ومساحة كل نموذج",
    ],
    en: [
      "New full-screen plan viewer with pinch or double-tap zoom",
      "Each plan split into named sheets: floors, elevations, sections",
      "Plan cards now show a thumbnail and each model's area",
    ],
  },
  {
    version: "1.7.5",
    dateAr: "9 أغسطس 2026",
    dateEn: "August 9, 2026",
    ar: [
      "تحسين شكل شريط الخانات على الجوال — صف منظّم بدل التفاف عشوائي",
    ],
    en: [
      "Improved the mobile tabs layout — a clean grid instead of a messy wrap",
    ],
  },
  {
    version: "1.7.4",
    dateAr: "9 أغسطس 2026",
    dateEn: "August 9, 2026",
    ar: [
      "إضافة تبويب \"المخططات والمستندات\" لعرض مخططات الفيلا",
    ],
    en: [
      "Added a \"Plans & Documents\" tab for villa plans",
    ],
  },
  {
    version: "1.7.3",
    dateAr: "9 أغسطس 2026",
    dateEn: "August 9, 2026",
    ar: [
      "تصحيح حالة إغلاق استفسار رقم ٣٦",
    ],
    en: [
      "Corrected the closure status of inquiry #36",
    ],
  },
  {
    version: "1.7.2",
    dateAr: "8 أغسطس 2026",
    dateEn: "August 8, 2026",
    ar: [
      "حذف كود غير مستخدم إطلاقًا من الواجهة",
      "إعادة تنظيم الملف بفهرس وعناوين أقسام أوضح لتسهيل التعديل مستقبلاً",
    ],
    en: [
      "Removed code with zero references from the live UI",
      "Reorganized the file with a table of contents and clearer section headers",
    ],
  },
  {
    version: "1.7.1",
    dateAr: "8 أغسطس 2026",
    dateEn: "August 8, 2026",
    ar: [
      "تحسينات تقنية داخلية على رصد الأداء",
    ],
    en: [
      "Internal technical improvements to performance monitoring",
    ],
  },
  {
    version: "1.7.0",
    dateAr: "8 أغسطس 2026",
    dateEn: "August 8, 2026",
    ar: [
      "تصغير خفيف للبطاقة عند الضغط عليها",
      "رقم الاستفسار كعلامة مائية باهتة داخل كل بطاقة",
      "خط تقدّم تمرير رفيع أعلى الصفحة",
      "زجاجية تدريجية على شريط الخانات الملتصق عند التمرير",
      "تصحيح عنوان تبويب المتصفح",
    ],
    en: [
      "Subtle scale-down effect on card tap",
      "Faint watermark of the inquiry number inside each card",
      "Thin scroll-progress line at the top of the page",
      "Progressive glass effect on the sticky tab bar while scrolling",
      "Fixed the browser tab title",
    ],
  },
  {
    version: "1.6.0",
    dateAr: "8 أغسطس 2026",
    dateEn: "August 8, 2026",
    ar: [
      "مشاركة الاستفسار عبر نافذة المشاركة الأصلية بالجهاز (واتساب، تليجرام، رسائل...)",
      "زر رجوع الجهاز يقفل لوحة التفاصيل أو سجل الإصدارات بدل الخروج من الصفحة",
      "تنقّل سابق/تالي بين الاستفسارات داخل اللوحة، بالأزرار أو بسحب الإصبع",
      "البحث يقبل رقم الاستفسار مباشرة",
      "شريط فلاتر مصغّر يلتصق أعلى الشاشة عند التمرير بلوحة المتابعة",
      "زر \u200f\"رجوع للأعلى\"\u200f عائم",
      "تحميل الملاحظات الإضافية تلقائي عند التمرير، بدل زر \u200f\"عرض المزيد\"\u200f",
    ],
    en: [
      "Share Inquiry now opens the device's native share sheet (WhatsApp, Telegram, Messages...)",
      "Device back button closes the detail sheet or update log instead of leaving the page",
      "Previous/next navigation between inquiries inside the sheet, via buttons or swipe",
      "Search now accepts an inquiry number directly",
      "Compact filter bar sticks to the top while scrolling the Notes Board",
      "Floating \"Back to top\" button",
      "Loading more notes is now automatic on scroll, replacing the \"Show more\" button",
    ],
  },
  {
    version: "1.5.2",
    dateAr: "8 أغسطس 2026",
    dateEn: "August 8, 2026",
    ar: [
      "زر \u200f\"مشاركة الاستفسار\"\u200f جديد داخل لوحة تفاصيل كل استفسار — ينسخ رابطًا مباشرًا لهذا الاستفسار تحديدًا مع تأكيد بصري (شريط أخضر ينزلق) بنفس أسلوب زر \u200f\"ملخص\"\u200f",
      "الرابط المنسوخ يفتح اللوحة على نفس الاستفسار مباشرة عند لصقه ومشاركته لأي شخص",
      "زرّا \u200f\"لايك\"\u200f و\u200f\"ديسلايك\"\u200f جديدان بجانب زر \u200f\"مشاركة\"\u200f داخل نفس اللوحة — أيقونتا يد واضحتان بدون أي عدّاد ظاهر بالواجهة",
    ],
    en: [
      "New \"Share Inquiry\" button inside each inquiry's detail sheet — copies a direct link to that specific inquiry with a visual confirmation (sliding green bar), matching the existing \"Summary\" button style",
      "The copied link opens the dashboard directly on that same inquiry when pasted and shared with anyone",
      "New \"Like\" and \"Dislike\" buttons next to the \"Share\" button in the same sheet — clear thumb icons with no visible counter on screen",
    ],
  },
  {
    version: "1.5.1",
    dateAr: "8 أغسطس 2026",
    dateEn: "August 8, 2026",
    ar: [
      "زر \u200f\"مجتمع الملاك\"\u200f جديد بأعلى اللوحة (بأيقونة تليجرام) يفتح رابط مجموعة الملاك مباشرة في تبويب جديد",
    ],
    en: [
      "New \"Owners Community\" button at the top of the dashboard (with Telegram icon) opens the owners group link directly in a new tab",
    ],
  },
  {
    version: "1.5.0",
    dateAr: "7 أغسطس 2026",
    dateEn: "August 7, 2026",
    ar: [
      "الأرقام الرئيسية (إجمالي الملاحظات، توزيع الحالات، المفتوحة والمقفلة، نسبة الاعتماد) صارت تعدّ تصاعديًا من صفر كل مرة تدخل الشاشة أثناء التمرير",
      "شريط توزيع الحالات ينمو من صفر عند ظهوره، بنفس روح أشرطة تقدّم التنفيذ",
      "صف حلقات جديد أعلى المراحل بخانة تقدم التنفيذ: ملخص بصري سريع يرتسم تدريجيًا، بنفس ألوان المتقدّم والمتأخّر — والأشرطة التفصيلية تحته كما هي بلا تغيير",
      "وميض خفيف يمر على بطاقة الاستفسار لحظة الضغط عليها، ولوحة التفاصيل تنزلق من أسفل الشاشة بالكامل بدل الظهور المفاجئ",
      "توهج هادئ ينبض حول شارة \u200f\"الجديد\"\u200f، ونبضة صغيرة تكبّر الفلتر المختار عند اختياره",
      "عدد النتائج يقفز قفزة صغيرة عند تغيّره بعد الفلترة، وانتقال ناعم عند التبديل بين عرض البطاقات والجدول",
      "زر \u200f\"ملخص\"\u200f صار يعرض شريطًا أخضر ينزلق داخله عند نجاح النسخ بدل تغيير الأيقونة فقط",
      "أثناء تحميل أحدث نسخة، يظهر هيكل رمادي متحرك بدل النص — مع بقاء كل البيانات ظاهرة ولا تُخفى",
      "تنظيف إضافي: حذف بقايا تنسيقات CSS غير مستخدمة تبقّت من تنظيف الإصدار السابق",
    ],
    en: [
      "Key figures (total notes, status breakdown, open and closed counts, approval rate) now count up from zero each time they enter the screen while scrolling",
      "The status breakdown bar grows from zero when it appears, matching the execution progress bars",
      "A new ring row above the phases in the Progress tab: a quick visual summary that draws in gradually, using the same ahead/behind colors — the detailed bars below remain unchanged",
      "A soft flash sweeps across an inquiry card the moment it's tapped, and the detail sheet now slides up fully from the bottom of the screen instead of appearing abruptly",
      "A gentle glow pulses around the \"New\" badge, and a small bounce scales up the selected filter chip",
      "The results count bounces slightly when it changes after filtering, and switching between card and table views now transitions smoothly",
      "The \"Summary\" button now shows a green bar sliding up inside it on a successful copy, instead of only swapping the icon",
      "While loading the latest version, an animated gray placeholder replaces the text — all data stays visible and is never hidden",
      "Additional cleanup: removed leftover unused CSS rules remaining from the previous version's cleanup",
    ],
  },
  {
    version: "1.4.4",
    dateAr: "7 أغسطس 2026",
    dateEn: "August 7, 2026",
    ar: [
      "تنظيف داخلي فقط: حذف كود غير مستخدم إطلاقًا من الواجهة (~480 سطر، ١٧٪ من حجم الملف) — لوحتا رفع تحديث كانتا معطّلتين تمامًا مع محرك قراءة ملفات Excel/CSV المرتبط بهما، ودوال مساعدة صارت بلا استخدام بعد إزالتهما",
      "شمل الحذف أيضًا استيراد مكتبة خارجية (xlsx) لم تعد مستخدمة أبدًا في أي مكان بالتطبيق",
      "لا يوجد أي تغيير في الشكل أو السلوك أو البيانات الظاهرة للمستخدم — الملف الناتج مطابق حرفيًا للسابق فيما يخص كل الأجزاء الحية، تم التحقق بمقارنة سطر بسطر",
    ],
    en: [
      "Internal cleanup only: removed ~480 lines (17% of the file) of code with zero references from the live UI — two update-upload panels that were fully disconnected, along with the Excel/CSV parsing engine that only fed them, and helper functions left unused once those were removed",
      "Also removed an external library import (xlsx) that was no longer used anywhere in the app",
      "No change to appearance, behavior, or data shown to users — the resulting file is byte-identical to the previous one for every live code path, verified with a line-by-line diff",
    ],
  },
  {
    version: "1.4.3",
    dateAr: "7 أغسطس 2026",
    dateEn: "August 7, 2026",
    ar: [
      "إصلاح تشوّه شكل الحروف بخط العنوان الزخرفي \u200f\"Reem Kufi\"\u200f عند فتح الصفحة لأول مرة — كان المتصفح يرسم النص بخط بديل مؤقت قبل اكتمال تحميل الخط الأصلي مما يشوّه الحروف العربية للحظة",
      "الآن ينتظر المتصفح تحميل الخط كاملًا قبل رسم العنوان، فيظهر بشكله الصحيح من أول لحظة بدون أي تشوّه أو حاجة لتحديث الصفحة",
    ],
    en: [
      "Fixed distorted lettering in the decorative \"Reem Kufi\" heading font on first page load — the browser was painting the text with a temporary fallback font before the real font finished loading, briefly garbling the Arabic shaping",
      "The browser now waits for the font to fully load before painting the heading, so it renders correctly from the first frame without needing a page refresh",
    ],
  },
  {
    version: "1.4.2",
    dateAr: "7 أغسطس 2026",
    dateEn: "August 7, 2026",
    ar: [
      "شريط التبويبات الرئيسي (نظرة عامة / متابعة الملاحظات / تقدم التنفيذ) صار له انتقال ناعم: تلاشي خفيف لمحتوى التبويب الجديد، ومؤشر رفيع بلون الهوية ينزلق تحت التبويب النشط",
      "المؤشر يحسب موضعه تلقائيًا حسب اتجاه اللغة (عربي/إنجليزي) وحجم الشاشة، بما في ذلك وضع سطح المكتب",
    ],
    en: [
      "The main tab bar (Overview / Notes Board / Progress) now has a smooth transition: a soft fade for the new tab's content, and a thin accent-colored indicator that slides under the active tab",
      "The indicator auto-calculates its position based on language direction (Arabic/English) and screen size, including desktop mode",
    ],
  },
  {
    version: "1.4.1",
    dateAr: "7 أغسطس 2026",
    dateEn: "August 7, 2026",
    ar: [
      "خانة \u200f\"تقدم التنفيذ\"\u200f فقط: أشرطة التقدّم (الإجمالي، المراحل، والبلوكات) صارت تفضى وتتعبى من جديد كل مرة تدخل نطاق الشاشة أثناء التمرير، مع لمعة ناعمة تمر عليها بعد اكتمال التعبئة",
      "لون الشريط لم يتغيّر: أخضر للمتقدّم، أحمر للمتأخّر، رمادي بلا بيانات — نفس المنطق السابق تمامًا",
      "إعداد \u200f\"تقليل الحركة\"\u200f بالجهاز مُحترَم بالكامل: الأشرطة تظهر فورًا بدون انتظار سكرول لمن يفعّله",
    ],
    en: [
      "\"Progress\" tab only: progress bars (total, phases, and blocks) now empty out and re-fill each time they enter the screen while scrolling, with a soft shimmer sweep once the fill completes",
      "Bar color is unchanged: green for ahead, red for behind, gray for no data — identical to the previous logic",
      "The device's \"reduce motion\" setting is fully respected: bars appear instantly with no scroll wait for those who enable it",
    ],
  },
  {
    version: "1.4.0",
    dateAr: "5 أغسطس 2026",
    dateEn: "August 5, 2026",
    ar: [
      "هدف التنفيذ صار يُحسب من التقويم مباشرة ويتقدّم شهريًا بنفسه — للمشروع كاملًا ولكل مرحلة وكل بلوك — سواء وصلت قراءة المطور الشهرية أو لا",
      "الخطة المعتمدة: ٣٫١٢٥ نقطة شهريًا، أي ١٠٠٪ خلال ٣٢ شهرًا حتى ديسمبر ٢٠٢٧، وهي مطابقة تمامًا للأهداف المسجَّلة سابقًا",
      "إضافة لوحة \u200f\"هدف هذا الشهر\"\u200f تعرض هدف الشهر الجاري وآخر قراءة وصلت من المطور والفارق بينهما",
      "الأشهر التي لم تصل قراءتها تظهر باهتة في شريط الأشهر، بهدف محسوب وإنجاز فارغ بدل ترحيل أرقام قديمة",
      "عناوين الفترات والسنوات صارت تُحسب تلقائيًا بدل كتابتها يدويًا، والرسم الزمني يعرض آخر ١٢ شهرًا كحد أقصى",
    ],
    en: [
      "The execution target is now derived from the calendar and advances monthly on its own — for the whole project, each phase and each block — whether or not the developer's monthly reading has arrived",
      "Approved plan: 3.125 points per month, i.e. 100% over 32 months through December 2027, matching the previously recorded targets exactly",
      "Added a \"This month's target\" panel showing the current month's target, the latest reading received from the developer, and the difference between them",
      "Months with no reading yet appear faded in the month bar, with a computed target and empty progress instead of carrying old figures forward",
      "Period and year labels are now computed automatically instead of being written by hand, and the timeline chart shows at most the last 12 months",
    ],
  },
  {
    version: "1.3.0",
    dateAr: "5 أغسطس 2026",
    dateEn: "August 5, 2026",
    ar: [
      "إضافة زر \u200f\"سطح المكتب\"\u200f في رأس الصفحة يحوّل الصفحة كاملة إلى عرض متصفح مكتبي — نفس مبدأ \u200f\"طلب موقع الكمبيوتر\"\u200f في المتصفح",
      "عند تفعيله تُرسم الصفحة بعرض 1180 بكسل وتُصغَّر لتناسب الشاشة، ويمكن التقريب بالأصبعين، وتتحوّل النتائج تلقائيًا إلى عرض الجدول",
      "الزر يتحوّل إلى \u200f\"عرض الجوال\"\u200f للرجوع، ولا يظهر إطلاقًا على الأجهزة التي عرضها الفعلي 1024 بكسل فأكثر لعدم الحاجة له",
    ],
    en: [
      "Added a \"Desktop\" button in the page header that switches the whole page to a desktop browser layout — the same idea as \"Request Desktop Website\" in a browser",
      "When active the page is laid out at 1180px and scaled to fit the screen, pinch-to-zoom works, and results switch to table view automatically",
      "The button becomes \"Mobile view\" to switch back, and never appears on devices whose actual screen is 1024px or wider, where it serves no purpose",
    ],
  },
  {
    version: "1.2.0",
    dateAr: "5 أغسطس 2026",
    dateEn: "August 5, 2026",
    ar: [
      "إضافة زر تبديل شكل عرض النتائج (بطاقات / جدول) في نهاية سطر \u200f\"النتائج\"\u200f داخل خانة متابعة الملاحظات",
      "الزر متاح على كل الأجهزة: الافتراضي بطاقات على الجوال وجدول على الشاشات 1024 بكسل فأكثر، ومن يريد وضع سطح المكتب على جواله يختاره بنفسه ويبقى مثبتًا",
      "في عرض الجدول على الشاشات الصغيرة يتم التمرير أفقيًا داخل إطار الجدول وحده دون تصغير الصفحة",
    ],
    en: [
      "Added a results layout toggle (cards / table) at the end of the \"Results\" line inside the Notes Board tab",
      "Available on every device: cards by default on phones and table on screens 1024px and wider, and anyone who wants the desktop layout on their phone can select it and it stays selected",
      "On small screens the table scrolls horizontally inside its own frame without shrinking the page",
    ],
  },
  {
    version: "1.1.2",
    dateAr: "29 يوليو 2026",
    dateEn: "July 29, 2026",
    ar: ["حذف عدّاد \u200f\"ملاحظة\"\u200f وعدّاد \u200f\"مهندسين\"\u200f من شريط المعلومات أعلى الصفحة، واستبدال عدّاد النماذج بذكر أسماء النماذج نفسها"],
    en: ["Removed the \"notes\" and \"engineers\" counts from the top info bar, and replaced the models count with the actual model names"],
  },
  {
    version: "1.1.1",
    dateAr: "29 يوليو 2026",
    dateEn: "July 29, 2026",
    ar: ["حذف زر الطباعة من رأس الصفحة لعدم وجود فائدة منه"],
    en: ["Removed the Print button from the header as it served no purpose"],
  },
  {
    version: "1.1.0",
    dateAr: "29 يوليو 2026",
    dateEn: "July 29, 2026",
    ar: [
      "إضافة زر تبديل اللغة (ع/EN) داخل نافذة الإقرار القانوني",
      "حذف ملاحظة \u200f\"لم يُنشر تحديث بعد\"\u200f غير المفيدة من الصفحة الرئيسية وخانة تقدم التنفيذ",
      "تصحيح عرض السنة والأرقام عند التبديل للغة الإنجليزية في خانة تقدم التنفيذ",
      "تصحيح موقع خط الهدف داخل أشرطة تقدم التنفيذ ليطابق اتجاه الصفحة بالإنجليزية",
      "تبسيط رأس الصفحة وتذييلها بحذف نصوص لا تضيف فائدة",
      "إضافة رقم إصدار اللوحة وسجل التحديثات (هذه النافذة)",
    ],
    en: [
      "Added a language toggle (ع/EN) inside the legal disclaimer window",
      "Removed the unhelpful \"no update published yet\" notice from the main page and the Progress tab",
      "Fixed year and number rendering when switching to English on the Progress tab",
      "Fixed the target-line position inside progress bars to match page direction in English",
      "Simplified the page header and footer by removing text that added no value",
      "Added a dashboard version number and update log (this window)",
    ],
  },
  {
    version: "1.0.0",
    dateAr: "—",
    dateEn: "—",
    ar: [
      "الإصدار الأساسي للوحة: النظرة العامة، متابعة الملاحظات، تقدم التنفيذ، المخطط التفاعلي للفيلا، الوضع الفاتح/الداكن، ثنائية اللغة الكاملة",
    ],
    en: [
      "Baseline release: Overview, Notes Board, Progress, the interactive villa plan, light/dark mode, and full bilingual support",
    ],
  },
];
export const CURRENT_VERSION = CHANGELOG[0].version;

/* ── إقرار قانوني — يظهر في كل زيارة، بدون تذكّر الموافقة ── */
export const LEGAL_COPY = {
  ar: {
    eyebrow: "قبل ما تكمل",
    title: "تنويه وإخلاء مسؤولية قانونية",
    points: [
      ["طبيعة المنصة", "هذه اللوحة هي مبادرة واجتهاد شخصي وودّي من ممثلي الملاك، ولا تُعد منصة رسمية أو متحدثًا رسميًا باسم أي جهة حكومية، خريطة طريق، أو الشركة المطوّرة."],
      ["طبيعة البيانات", "كافة المعلومات والإحصائيات الواردة هي بيانات استرشادية منقولة كما هي من المطوّر العقاري أو من استبيانات الملاك، دون أدنى مسؤولية عن دقتها أو صحتها أو أي تغييرات قد تطرأ عليها مستقبلًا من قِبل المطوّر."],
      ["نفي الصفة والمسؤولية", "لا يتحمّل ممثلو الملاك أي مسؤولية قانونية أو مالية أو إدارية ناتجة عن استخدام هذه البيانات، أو بناء أي قرارات عليها، أو عن أي ردود فعل أو إجراءات قد تتخذها أي جهة أو مطوّر تجاه ما يُنقل من مطالب أو استفسارات."],
    ],
    consent: "بالضغط على «أوافق»، فأنت تقرّ بعلمك التام بجميع ما ورد أعلاه وتوافق على إخلاء مسؤولية القائمين على اللوحة تمامًا.",
    agree: "أوافق",
  },
  en: {
    eyebrow: "Before you continue",
    title: "Legal Notice & Disclaimer",
    points: [
      ["Nature of the Platform", "This dashboard is a personal, voluntary initiative by owner representatives. It is not an official platform or spokesperson on behalf of any government entity, project roadmap, or the developer company."],
      ["Nature of the Data", "All information and statistics shown are indicative data, transferred as-is from the real estate developer or from owner surveys, with no responsibility for their accuracy, correctness, or any future changes made by the developer."],
      ["Disclaimer of Role & Liability", "Owner representatives bear no legal, financial, or administrative liability arising from use of this data, decisions made based on it, or any response or action taken by any party or developer regarding demands or inquiries conveyed."],
    ],
    consent: "By clicking \u201cI Agree,\u201d you acknowledge full awareness of the above and agree to fully release the dashboard administrators from liability.",
    agree: "I Agree",
  },
};
